# Site settings
title: Joey's Tech Blog | 我的技术博客
email: joeyyu.van@gmail.com
author: Joey Yu
description:
url: https://blog.goplusgo.me

# Build settings
permalink: :title/
sass:
  sass_dir: assets/css

# Social icons
show_social_icons: true
linkedin_username: joey-yu-3616961a8
github_username: goplusgo

# plugins
plugins: [jekyll-paginate]
paginate: 4

# Sidebar
sidebar-avatar: /assets/images/avatar.jpg
sidebar-about-description: "Senior Software Engineer<br>Splunk, Vancouver, BC"

# this section is copied from: https://github.com/Huxpro/huxpro.github.io
# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Disqus Comments
disqus:
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: blog-goplusgo-me
